services:
  keycloak:
    extends:
      file: ../base/docker-compose.yaml
      service: keycloak
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
    env_file:
      keycloak.env
  femr:
    extends:
      file: ../base/docker-compose.yaml
      service: femr
    env_file:
      femr.env
  survey:
    extends:
      file: ../base/docker-compose.yaml
      service: survey
    env_file:
      survey.env
  confidentialbackend:
    extends:
      file: ../base/docker-compose.yaml
      service: confidentialbackend
    env_file:
      confidentialbackend.env
  redis:
    extends:
      file: ../base/docker-compose.yaml
      service: redis
  fhir-auth:
    extends:
      file: ../base/docker-compose.yaml
      service: fhir-auth
    env_file:
      fhir-auth.env
  aidbox:
    extends:
      file: ../base/docker-compose.yaml
      service: aidbox
    networks:
      # expose Aidbox to internet
      ingress:
    labels:
      # unauthenticated route
      - traefik.enable=true
      - traefik.http.routers.aidbox-${COMPOSE_PROJECT_NAME}.rule=Host(`aidbox.${BASE_DOMAIN}`)
      - traefik.http.routers.aidbox-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.aidbox-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    env_file:
      - aidbox.env
  db:
    extends:
      file: ../base/docker-compose.yaml
      service: db
volumes:
  db-data: {}
networks:
  # internal network for backing services
  internal:
  # ingress network
  ingress:
    external: true
    name: external_web
