services:
  femr:
    image: ghcr.io/uwcirg/cosri-patientsearch:${FEMR_IMAGE_TAG:-develop}
    env_file:
      femr.env
    environment:
      OIDC_AUTHORIZE_URL: https://keycloak.${BASE_DOMAIN}/auth/realms/fEMR/protocol/openid-connect/auth
      OIDC_CLIENT_ID: femr_openid_client
      OIDC_ISSUER: https://keycloak.${BASE_DOMAIN}/auth/realms/fEMR
      OIDC_REDIRECT_URIS: https://keycloak.${BASE_DOMAIN}/oidc_callback
      OIDC_USERINFO_URI: https://keycloak.${BASE_DOMAIN}/auth/realms/fEMR/protocol/openid-connect/userinfo
      OIDC_TOKEN_URI: https://keycloak.${BASE_DOMAIN}/auth/realms/fEMR/protocol/openid-connect/token
      OIDC_TOKEN_INTROSPECTION_URI: https://keycloak.${BASE_DOMAIN}/auth/realms/fEMR/protocol/openid-connect/token/introspect

      # FHIR URL passed to SoF client
      SOF_HOST_FHIR_URL: https://fhirwall.${BASE_DOMAIN}/fhir
      SOF_CLIENTS: '[{"id":"ENROLLMENT", "label":"Enrollment", "launch_url":"https://enrollment.${BASE_DOMAIN}/launch.html"},{"id":"MESSAGING", "label":"Messaging", "launch_url":"https://messaging.${BASE_DOMAIN}/launch.html"}]'
      REDIS_URL: redis://redis:6379/2
    depends_on:
      - fhirwall
      - keycloak
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.femr-${COMPOSE_PROJECT_NAME}.rule=Host(`femr.${BASE_DOMAIN}`)
      - traefik.http.routers.femr-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.femr-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      - ingress
      - internal
  confidentialbackend:
    image: ghcr.io/uwcirg/helloworld-confidential-client-sof:${CONFIDENTIALBACKEND_IMAGE_TAG:-latest}
    environment:
      APP_FHIR_URL: http://fhir-internal:8080/fhir
      REQUEST_CACHE_URL: redis://redis:6379/1
      SESSION_REDIS: redis://redis:6379/0

      PREFERRED_URL_SCHEME: https
      SESSION_COOKIE_SECURE: "true"
      # ultimate destination after SoF launch and backend auth
      LAUNCH_DEST: https://confidentialbackend.${BASE_DOMAIN}/launch.html

      # do not pass launch/patient as Epic will infer standalone launch
      LAUNCH_FHIR_SCOPES: user/*.read launch openid fhirUser
      # TODO remove once removed from uwcirg/helloworld-confidential-client-sof
      SOF_CLIENT_SCOPES: user/*.read launch openid fhirUser
    labels:
      - traefik.enable=true
      - traefik.http.routers.confidentialbackend-${COMPOSE_PROJECT_NAME}.rule=Host(`confidentialbackend.${BASE_DOMAIN}`) && (PathPrefix(`/auth`) || PathPrefix(`/fhir-router`) || PathPrefix(`/auditlog`))

      - traefik.http.routers.confidentialbackend-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.confidentialbackend-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    networks:
      - ingress
      - internal
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - internal
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-26.1}
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.rule=Host(`keycloak.${BASE_DOMAIN}`)
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    command:
      # https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup
      # recent Keycloak releases do not allow importing the master realm on startup; use old properties as workaround
      # https://github.com/keycloak/keycloak/issues/12544#issuecomment-1191846726
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=dir
      - -Dkeycloak.migration.dir=/opt/keycloak/data/import
      - -Dkeycloak.migration.strategy=IGNORE_EXISTING
      - -Dkeycloak.migration.replace-placeholders=true
      - start
      - --log-console-output=json
    environment:
      # https://www.keycloak.org/server/all-config
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      # https://www.keycloak.org/server/reverseproxy
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      # trust traefik Host headers
      KC_HOSTNAME_STRICT: "false"

      # logging
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: info
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_ERROR_LEVEL: error

      KEYCLOAK_ADMIN: admin

      KEYCLOAK_SHL_CREATOR_BASE: https://${BASE_DOMAIN}
      KEYCLOAK_SHL_CREATOR_LOGOUT_REDIRECT_URL: https://${BASE_DOMAIN}

    volumes:
      - ./config/keycloak/import/:/opt/keycloak/data/import:ro
    depends_on:
      - db
    networks:
      - ingress
      - internal

  aidbox:
    image: healthsamurai/aidboxone:${AIDBOX_IMAGE_TAG:-2510}
    environment:
      # https://www.health-samurai.io/docs/aidbox/reference/all-settings
      # deploy-specific details
      BOX_WEB_BASE_URL: https://aidbox.${BASE_DOMAIN}
      BOX_ADMIN_PASSWORD: ${BOX_ADMIN_PASSWORD:-admin}
      BOX_DB_HOST: db
      BOX_DB_DATABASE: aidbox
      BOX_DB_USER: postgres
      BOX_DB_PASSWORD: postgres

      # use recommended values over defaults
      BOX_BOOTSTRAP_FHIR_PACKAGES: "hl7.fhir.r4.core#4.0.1"
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_SETTINGS_MODE: read-write
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_JSON_SCHEMA_DATETIME_REGEX: "#{:fhir-datetime}"
      BOX_FHIR_SEARCH_INCLUDE_CONFORMANT: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
    depends_on:
      - db
    expose:
      - 8080
    networks:
      internal:
        aliases:
          - fhir-internal
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s
  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-18}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql
      # mount db creation script in place for bootstrap
      - ./config/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        - CMD
        - pg_isready
        - --user=postgres
        - --dbname=aidbox
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - internal
volumes:
  db-data: {}
networks:
  # internal network for backing services
  internal:
  # ingress network
  ingress:
    external: true
    name: external_web
